version: '3.8'
services:
  backend:
    command: ./gradlew bootRun
    volumes:
      - ./backend:/app
      - ~/.gradle:/home/gradle/.gradle
  frontend:
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
